'use client'

import { useState } from 'react'
import {
  ArrowRight,
  BookOpen,
  CalendarDays,
  Check,
  ChevronRight,
  CircleHelp,
  Compass,
  Flame,
  Leaf,
  Menu,
  MessageCircle,
  Play,
  Plus,
  Sparkles,
  Users,
  X,
  Zap,
} from 'lucide-react'

const welcomeVideo = 'https://www.youtube.com/embed/3JTM2o-1r5E?autoplay=1&mute=1&controls=1&rel=0&modestbranding=1&playsinline=1'

const collaboratorLogos = [
  { name: 'Adani', src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-dLoXDWnRnDS1HkG9HnyiRjtAkGFQRG.png' },
  { name: 'Esyasoft', src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-GW5HCYjzZqe3FCDBLzUFfY9xZdOUV0.png' },
  { name: 'Landis+Gyr', src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-3Q9BoKkHgfeL7pSTAF6n6kAUm1FeSk.png' },
]

const policies = [
  { title: 'Information Security', detail: 'Protect company systems, credentials, devices and confidential information. Follow all security and access-control procedures.' },
  { title: 'Code of Conduct', detail: 'Maintain professionalism, respect, integrity and inclusivity in all workplace interactions.' },
  { title: 'Data Privacy', detail: 'Handle employee, customer and business data responsibly and only for authorized purposes.' },
  { title: 'Acceptable Use', detail: 'Use company devices, networks, software and other resources responsibly and only for legitimate business purposes.' },
  { title: 'Confidentiality', detail: 'Do not disclose, copy or share confidential company, customer or project information without authorization.' },
  { title: 'Anti-Harassment & Equal Opportunity', detail: 'Maintain a safe, respectful workplace free from harassment, discrimination and inappropriate conduct.' },
  { title: 'Attendance & Leave', detail: 'Follow working hours, attendance procedures and leave-approval processes established by the company.' },
  { title: 'Social Media & Public Communication', detail: 'Do not share confidential information or represent personal opinions as official company statements.' },
  { title: 'Intellectual Property', detail: 'Respect company and third-party intellectual property. Work created as part of employment should be handled according to company policy.' },
  { title: 'Incident Reporting', detail: 'Report security incidents, policy violations, workplace concerns or suspicious activity through the appropriate internal channels.' },
]

const images = {
  founder: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images-sZLCMiKwXrtdxwtCOjtE4EsQew3I5P.jpg',
  hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-24%20at%2011.28.13%20AM-3YWpXFizNTZMMfozrMizffHtZerlmt.jpeg',
  stage: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-24%20at%2011.12.14%20AM%20%282%29-2iT8YdqxUU0knwlWHWY3vRa8ofLxXR.jpeg',
  community: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-24%20at%2011.12.14%20AM-X3MYNdKYfGc2xazwn45unPPIr4lRZL.jpeg',
}

const speakerSessions = [
  { type: 'Welcome keynote', speaker: 'Program leadership', role: 'Opening speakers', detail: 'A warm welcome to the 2026 graduate cohort, the story behind Esyasoft, and what to expect from your first 30 days.' },
  { type: 'People & culture', speaker: 'People team', role: 'Your support network', detail: 'Meet the people who help you settle in, understand how we work together, and find the right support whenever you need it.' },
  { type: 'Product deep dive', speaker: 'Product and domain leaders', role: 'Context builders', detail: 'Understand our products, customers, and the real-world problems behind the work you will contribute to.' },
  { type: 'Ask me anything', speaker: 'Subject-matter experts', role: 'Practitioners', detail: 'Bring your questions. Hear honest lessons from experienced teammates about projects, growth, and getting started well.' },
  { type: 'Your first contribution', speaker: 'Your manager and buddy', role: 'Day-to-day guides', detail: 'Choose a starter task, get feedback on your approach, and leave with a clear next step for month two.' },
]

const schedule = [
  ['1', 'Mon 7 Sep', 'Leadership Orientation', 'Divya'], ['2', 'Tue 8 Sep', 'HR & Culture Orientation', 'Divya'], ['3', 'Wed 9 Sep', 'Project Delivery Excellence', 'Deependra, Sachin'], ['4', 'Thu 10 Sep', 'Smart Meter & Data Acquisition', 'Rohit Patki'], ['5', 'Fri 11 Sep', 'MDMS & Data Intelligence', 'Amit Kulkarni, Pranav Kashyap'], ['—', 'Mon 14 Sep', 'Holiday · Ganesh Chaturthi', '—'], ['6', 'Tue 15 Sep', 'Smart Meters Portfolio', 'Anupam Das'], ['7', 'Wed 16 Sep', 'POSH & Soft Skills, Part 1', 'Vinol & team'], ['8', 'Thu 17 Sep', 'Unassigned · domain slot blank', '—'], ['9', 'Fri 18 Sep', 'Project Management & Agile Practices', 'Gopinath Arunachalam, Ankit Shrivastava'], ['10', 'Mon 21 Sep', 'BESS & Communication Tech', 'Alfred Manohar, Kassem Abdallah, Saurabh Kumar, Dushyant Singh'], ['11', 'Tue 22 Sep', 'EV Charging & CPMS', 'Ashwin Gautham, Kartik Kumar'], ['12', 'Wed 23 Sep', 'Gas Distribution Network', 'Amit Golhani'], ['13–18', '24 Sep – 1 Oct', 'Business Capability Development / Soft Skills · topics TBC', 'Kamal / Divya'], ['—', 'Fri 2 Oct', 'Holiday · Gandhi Jayanthi', '—'], ['19–23', '5–9 Oct', 'Technical Foundation · topics TBC', 'Sierra Learning / Esyasoft SMEs'], ['24–28', '12–16 Oct', 'Technical Foundation · topics TBC', 'Sierra Learning / Esyasoft SMEs'], ['29', 'Mon 19 Oct', 'Technical Foundation', 'Sierra Learning / Esyasoft SMEs'], ['—', 'Tue 20 Oct', 'Holiday · Dussehra', '—'], ['30', 'Wed 21 Oct', 'Technical Foundation + Volt final activation', 'Sierra Learning / Esyasoft SMEs'],
]

const steps = [
  { day: '01', label: 'Meet your people', icon: Users, title: 'Welcome & connect', window: 'Days 1–3', description: 'Settle in, meet your cohort, and learn who to turn to when you need context or support.', sessions: ['Welcome to Esyasoft and the graduate cohort', 'Meet your buddy, manager, and immediate team', 'Office tour, tools setup, and first-week checklist'], outcome: 'You leave your first three days knowing where to go, who to ask, and how your team works.' },
  { day: '02', label: 'Find your rhythm', icon: Compass, title: 'Ways of working', window: 'Days 4–7', description: 'See how ideas move from a conversation to a shipped outcome, and find a routine that helps you learn.', sessions: ['How teams communicate, plan, and share feedback', 'Shadow a stand-up, review, or customer conversation', 'Set your personal goals for the first month'], outcome: 'You have a clear weekly rhythm and a small, realistic goal to own.' },
  { day: '03', label: 'Learn the domain', icon: BookOpen, title: 'Product & customer context', window: 'Days 8–14', description: 'Build the context behind our work: the products, customers, problems, and decisions that shape the business.', sessions: ['Product walkthrough and domain vocabulary', 'Customer journey: who we serve and why it matters', 'Ask-me-anything with a subject-matter expert'], outcome: 'You can explain what we build, who it helps, and where your work fits.' },
  { day: '04', label: 'Build your edge', icon: Zap, title: 'Practice & contribute', window: 'Days 15–30', description: 'Turn your learning into action with a guided starter project, feedback, and a plan for what comes next.', sessions: ['Pick a starter task with your manager', 'Pair with a teammate and share an early draft', '30-day reflection and next-step conversation'], outcome: 'You finish with a first contribution, useful feedback, and momentum for month two.' },
]

export function OnboardingDashboard() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeStep, setActiveStep] = useState(0)
  const [checked, setChecked] = useState(false)
  const [aboutOpen, setAboutOpen] = useState(false)
  const [policyOpen, setPolicyOpen] = useState<number | null>(null)

  return (
    <main className="min-h-screen overflow-hidden bg-[#f5f8f1] text-[#102c24]">
      <div className="fixed inset-0 -z-0 overflow-hidden pointer-events-none">
        <div className="absolute -left-32 top-40 h-80 w-80 rounded-full bg-[#c8ff39]/30 blur-3xl" />
        <div className="absolute right-0 top-[30rem] h-96 w-96 rounded-full bg-[#b3e8da]/40 blur-3xl" />
      </div>

      <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
        <a href="#top" className="flex items-center gap-2 font-bold tracking-tight" aria-label="Esyasoft Graduate Program home">
          <span className="grid h-9 w-9 place-items-center rounded-full bg-[#a9f229] text-[#102c24]"><Leaf size={18} strokeWidth={2.5} /></span>
          <span className="text-lg">esya<span className="text-[#57b85c]">soft</span></span>
        </a>
        <div className="hidden items-center gap-8 text-sm font-semibold md:flex">
          <a href="#start" className="transition-colors hover:text-[#57b85c]">Start here</a>
          <a href="#journey" className="transition-colors hover:text-[#57b85c]">Your journey</a>
          <a href="#schedule" className="transition-colors hover:text-[#57b85c]">Schedule</a>
          <a href="#community" className="transition-colors hover:text-[#57b85c]">Community</a>
          <a href="#about" className="rounded-full border border-[#102c24]/20 px-4 py-2 transition-all hover:border-[#102c24] hover:bg-white">About Esyasoft</a>
        </div>
        <button className="grid h-10 w-10 place-items-center rounded-full border border-[#102c24]/15 bg-white md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>
          {menuOpen ? <X size={19} /> : <Menu size={19} />}
        </button>
      </nav>
      {menuOpen && <div className="relative z-20 mx-5 rounded-2xl border border-[#102c24]/10 bg-white p-4 shadow-lg md:hidden"><div className="grid gap-3 text-sm font-semibold"><a href="#start" onClick={() => setMenuOpen(false)}>Start here</a><a href="#journey" onClick={() => setMenuOpen(false)}>Your journey</a><a href="#schedule" onClick={() => setMenuOpen(false)}>Schedule</a><a href="#community" onClick={() => setMenuOpen(false)}>Community</a></div></div>}

      <section id="top" className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-10 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-28 lg:pt-20">
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-700">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#84c957]/40 bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[.18em] text-[#428c4c]"><Sparkles size={14} /> Graduate program 2026</div>
          <h1 className="max-w-3xl text-5xl font-black leading-[.93] tracking-[-.055em] sm:text-7xl">Your first 30 days.<br /><span className="text-[#59bd4e]">Made simple.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-[#41615a]">Welcome to Esyasoft. Think of this as your friendly map for finding your people, learning how things work, and building something you&apos;ll be proud of.</p>
          <div className="mt-8 flex flex-wrap gap-3"><a href="#start" className="group inline-flex items-center gap-3 rounded-full bg-[#102c24] px-6 py-3.5 text-sm font-bold text-white shadow-[0_10px_25px_rgba(16,44,36,.18)] transition-all hover:-translate-y-1 hover:bg-[#1f5143]">Show me the way <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></a><a href="#journey" className="inline-flex items-center gap-2 rounded-full border border-[#102c24]/15 bg-white/60 px-5 py-3.5 text-sm font-bold transition-all hover:bg-white"><Play size={15} fill="currentColor" /> See the journey</a></div>
          <div className="mt-10 flex items-center gap-3 text-sm text-[#56746b]"><div className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f5f8f1] bg-[#bceba3] text-xs font-bold">A</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f5f8f1] bg-[#ffd39d] text-xs font-bold">R</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f5f8f1] bg-[#b9d9ff] text-xs font-bold">S</span></div><span>Join 40+ new explorers</span></div>
        </div>
        <div className="relative animate-in fade-in zoom-in-95 duration-1000">
          <div className="absolute -right-2 top-4 z-10 rotate-6 rounded-2xl bg-[#a9f229] px-4 py-3 text-xs font-black uppercase tracking-wider text-[#102c24] shadow-lg sm:right-8">Explore · Grow · Prosper</div>
          <div className="overflow-hidden rounded-[2.2rem] border-[10px] border-white bg-[#102c24] shadow-2xl shadow-[#1c513b]/15"><div className="border-b border-white/10 p-3"><div className="mb-2 flex items-center justify-between px-1"><p className="text-xs font-black uppercase tracking-[.16em] text-[#b8f73a]">Start here · welcome video</p><span className="h-2 w-2 animate-pulse rounded-full bg-[#b8f73a]" /></div><div className="aspect-video overflow-hidden rounded-2xl bg-black"><iframe className="h-full w-full" src={welcomeVideo} title="Esyasoft Graduate Program welcome video" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /></div></div><div className="relative aspect-[1.15] overflow-hidden sm:aspect-[1.35] lg:aspect-[1.05]"><img src={images.hero} alt="Esyasoft Graduate Program 2026 welcome artwork" className="h-full w-full object-cover object-left transition-transform duration-700 hover:scale-105" /><div className="absolute bottom-4 left-4 rounded-full bg-[#102c24]/85 px-3 py-2 text-xs font-bold text-white backdrop-blur"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#b8f73a]" />Welcome to your first 30 days</div></div></div>
          <div className="absolute -bottom-5 -left-3 rounded-2xl border border-white/70 bg-white/90 p-4 shadow-xl backdrop-blur sm:left-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaffd1] text-[#4da749]"><Flame size={20} /></span><div><p className="text-xs text-[#678079]">Today&apos;s energy</p><p className="font-black">Curious &amp; ready</p></div></div></div>
        </div>
      </section>

      <section id="start" className="relative z-10 border-y border-[#102c24]/8 bg-white/60 px-5 py-16 sm:px-8 lg:py-24">
        <div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">Before you begin</p><h2 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">No silly questions.<br />Just good <span className="text-[#59bd4e]">first steps.</span></h2><p className="mt-5 leading-7 text-[#55716a]">You don&apos;t need to know everything on day one. Start with these four small moves and let the rest unfold.</p></div>
          <div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map((step, index) => { const Icon = step.icon; const isActive = activeStep === index; return <button key={step.day} onClick={() => setActiveStep(index)} className={`group relative rounded-3xl p-5 text-left transition-all duration-300 ${isActive ? 'bg-[#102c24] text-white shadow-xl shadow-[#102c24]/15 -translate-y-1' : 'border border-[#102c24]/10 bg-[#f7faf4] hover:-translate-y-1 hover:bg-white'}`}><div className="flex items-start justify-between"><span className={`text-xs font-black ${isActive ? 'text-[#b8f73a]' : 'text-[#70b76c]'}`}>STEP {step.day}</span><Icon size={20} className={isActive ? 'text-[#b8f73a]' : 'text-[#74a98a'} /></div><p className="mt-12 font-black">{step.label}</p><ChevronRight size={16} className={`absolute bottom-5 right-5 transition-transform group-hover:translate-x-1 ${isActive ? 'text-[#b8f73a]' : 'text-[#9ab2a9'}`} /></button> })}</div>
          {(() => { const selected = steps[activeStep]; return <div className="mt-6 overflow-hidden rounded-3xl border border-[#102c24]/10 bg-white shadow-sm"><div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaffd1] text-sm font-black text-[#4d994b]">{selected.day}</span><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#62b95b]">{selected.window}</p><h3 className="text-2xl font-black tracking-tight">{selected.title}</h3></div></div><p className="mt-5 leading-7 text-[#55716a]">{selected.description}</p><div className="mt-5 rounded-2xl bg-[#f1f9e9] p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-[#4d994b]">By the end of this phase</p><p className="mt-2 text-sm font-semibold leading-6 text-[#315e3c]">{selected.outcome}</p></div></div><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#62b95b]">What happens in the sessions</p><ol className="mt-4 space-y-3">{selected.sessions.map((session, index) => <li key={session} className="flex items-start gap-3 rounded-2xl bg-[#f7faf4] p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#102c24] text-xs font-black text-[#b8f73a]">{index + 1}</span><span className="text-sm font-semibold leading-6 text-[#315e3c]">{session}</span></li>)}</ol></div></div></div> })()}
          <div className="mt-8 rounded-3xl border border-[#102c24]/10 bg-[#f7faf4] p-6 sm:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#62b95b]">Who you&apos;ll hear from</p><h3 className="mt-2 text-2xl font-black tracking-tight">Meet your session speakers</h3></div><Users className="hidden text-[#62b95b] sm:block" size={28} /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{speakerSessions.map((session) => <article key={session.type} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#62b95b]">{session.type}</p><h4 className="mt-1 font-black">{session.speaker}</h4><p className="text-xs font-semibold text-[#7a9188]">{session.role}</p></div><MessageCircle className="shrink-0 text-[#b5df8d]" size={18} /></div><p className="mt-3 text-sm leading-6 text-[#55716a]">{session.detail}</p></article>)}</div></div>
          <div className="mt-6 flex flex-col gap-4 rounded-3xl bg-[#eaffd1] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-start gap-3"><CircleHelp className="mt-0.5 shrink-0 text-[#4d994b]" size={20} /><p className="max-w-2xl text-sm leading-6 text-[#315e3c]"><strong>New here?</strong> That&apos;s exactly where you&apos;re meant to be. Find a buddy, ask one question, and write down one thing you learned today.</p></div><button onClick={() => setChecked(!checked)} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#315e3c] shadow-sm transition hover:shadow-md">{checked && <Check size={15} />} {checked ? 'I’m ready' : 'Mark as read'}</button></div>
        </div>
      </section>

      <section id="about" className="relative z-10 overflow-hidden bg-[#102c24] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="relative mx-auto w-full max-w-sm"><div className="absolute -inset-4 rounded-[2.5rem] bg-[#b8f73a]/20 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border-8 border-white/10 bg-[#f1f4ee]"><img src={images.founder} alt="Dr. Bipin Chandra, founder and Group CEO of Esyasoft" className="aspect-[.92] w-full object-cover object-top grayscale-[.12] transition duration-700 hover:scale-105" /><div className="bg-[#102c24] px-5 py-4"><p className="text-lg font-black text-white">Dr. Bipin Chandra</p><p className="mt-1 text-xs font-bold uppercase tracking-[.16em] text-[#b8f73a]">Founder &amp; Group CEO</p></div></div><div className="absolute -bottom-5 -right-4 rounded-2xl bg-[#b8f73a] px-4 py-3 text-[#102c24] shadow-xl"><p className="text-xs font-black uppercase tracking-[.16em]">Founded 2014</p><p className="mt-1 text-sm font-bold">Built for better energy</p></div></div><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#b8f73a]">The company behind the journey</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-6xl">Technology with<br /><span className="text-[#b8f73a]">a human pulse.</span></h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Esyasoft is a global energy transition technology group helping utilities build smarter grids, cleaner mobility, and more resilient communities.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-2xl font-black text-[#b8f73a]">12+</p><p className="mt-1 text-xs text-white/60">countries reached</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-2xl font-black text-[#b8f73a]">40+</p><p className="mt-1 text-xs text-white/60">utilities served</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-2xl font-black text-[#b8f73a]">200M+</p><p className="mt-1 text-xs text-white/60">end consumers</p></div></div></div></div></section>

      <section id="collaborators" className="relative z-10 border-y border-[#102c24]/10 bg-[#eaffd1] px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#4d994b]">Built together</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Our collaborators</h2></div><p className="max-w-md text-sm leading-6 text-[#315e3c]">Partnerships help us move ambitious energy ideas into the real world.</p></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{collaboratorLogos.map((logo) => <div key={logo.name} className="flex h-24 items-center justify-center rounded-2xl border border-[#315e3c]/10 bg-white px-5 transition hover:-translate-y-1 hover:shadow-lg"><img src={logo.src} alt={`${logo.name} collaborator logo`} className="max-h-10 max-w-[130px] object-contain opacity-70 grayscale transition hover:opacity-100 hover:grayscale-0" /></div>)}</div></div></section>

      <section id="policies" className="relative z-10 px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">How we operate</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Policies that<br /><span className="text-[#59bd4e]">guide the work.</span></h2><p className="mt-5 max-w-md leading-7 text-[#55716a]">Click a policy to open its short guide. These principles shape how we build, partner, and grow.</p></div><div className="space-y-3">{policies.map((policy, index) => <div key={policy.title} className="overflow-hidden rounded-2xl border border-[#102c24]/10 bg-white shadow-sm"><button onClick={() => setPolicyOpen(policyOpen === index ? null : index)} className="flex w-full items-center justify-between gap-4 p-5 text-left font-black"><span className="flex items-center gap-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaffd1] text-xs text-[#4d994b]">0{index + 1}</span>{policy.title}</span><Plus size={19} className={`shrink-0 text-[#4d994b] transition-transform ${policyOpen === index ? 'rotate-45' : ''}`} /></button>{policyOpen === index && <p className="border-t border-[#102c24]/8 px-5 pb-5 pl-[4.75rem] text-sm leading-7 text-[#55716a]">{policy.detail}</p>}</div>)}</div></div></section>

      <section id="week-one" className="relative z-10 border-y border-[#102c24]/8 bg-[#eff9e7] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">Week 1 · Power Core</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">Understand Esyasoft<br /><span className="text-[#59bd4e]">from the inside out.</span></h2><p className="mt-4 max-w-2xl leading-7 text-[#55716a]">Your first week builds confidence through five practical steps: tools, vision, structure, security, and values.</p></div><div className="rounded-2xl bg-white px-5 py-4 shadow-sm"><p className="text-xs font-black uppercase tracking-[.15em] text-[#4d994b]">Volt meter</p><p className="mt-1 text-2xl font-black text-[#102c24]">0% <span className="text-[#62b95b]">→</span> 20%</p></div></div><div className="mt-8 grid gap-3 md:grid-cols-5">{[['01','System Boot','Set up tools, access, and credentials.'],['02','Vision & Mission','Learn our story, leadership, and impact.'],['03','Organizational Matrix','Meet teams, stakeholders, and roles.'],['04','Security & Compliance','Understand privacy, IP, and workspace rules.'],['05','Ethics & Values','Practice accountability and continuous learning.']].map(([day, title, detail]) => <article key={day} className="rounded-2xl border border-[#102c24]/8 bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg"><span className="text-xs font-black text-[#62b95b]">DAY {day}</span><h3 className="mt-3 font-black text-[#102c24]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#55716a]">{detail}</p></article>)}</div><div className="mt-6 rounded-2xl bg-[#102c24] p-5 text-white"><p className="text-sm leading-6 text-white/80"><strong className="text-[#b8f73a]">Checkpoint:</strong> Complete the ecosystem quiz and log three 15-minute coffee chats to activate your Power Core.</p></div></div></section>

      <section id="progress" className="relative z-10 bg-[#102c24] px-5 py-16 text-white sm:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#b8f73a]">Build Volt</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Your progress tracker.</h2><p className="mt-4 max-w-2xl leading-7 text-white/65">Move through five cores, charge your Volt Meter, and reach full activation by Day 30.</p></div><div className="rounded-2xl bg-white/10 px-5 py-4"><p className="text-xs font-black uppercase tracking-[.16em] text-[#b8f73a]">Volt Meter</p><p className="mt-1 text-3xl font-black">0% <span className="text-[#b8f73a]">→</span> 100%</p></div></div><div className="mt-9 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/5 rounded-full bg-[#b8f73a]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-5">{[['01','Power Core','0–20%'],['02','Domain Core','20–40%'],['03','Neural Core','40–60%'],['04','Engine Core','60–80%'],['05','Drive Core','80–100%']].map(([number, title, range]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center justify-between"><span className="text-xs font-black text-[#b8f73a]">CORE {number}</span><span className="text-xs font-bold text-white/45">{range}</span></div><p className="mt-3 font-black">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">Checkpoint unlocks the next stage.</p></div>)}</div></div></section>

      <section id="schedule" className="relative z-10 border-y border-[#102c24]/8 bg-white/70 px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">The full 30-day plan</p><h2 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">Your journey,<br /><span className="text-[#59bd4e]">day by day.</span></h2><p className="mt-4 max-w-2xl leading-7 text-[#55716a]">Use this schedule as your simple map. Every row tells you what is happening, who owns the session, and what comes next.</p></div><div className="flex items-center gap-2 rounded-2xl bg-[#eaffd1] px-4 py-3 text-sm font-bold text-[#315e3c]"><CalendarDays size={18} /> 30 training days</div></div><div className="mt-8 overflow-hidden rounded-[2rem] border border-[#102c24]/10 bg-white shadow-xl shadow-[#102c24]/5"><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left"><caption className="sr-only">Graduate program 2026 day-by-day session schedule</caption><thead><tr className="bg-[#102c24] text-xs uppercase tracking-[.14em] text-[#b8f73a]"><th className="px-5 py-4">Day</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Session</th><th className="px-5 py-4">Speaker / owner</th></tr></thead><tbody>{schedule.map(([day, date, session, owner], index) => { const holiday = session.startsWith('Holiday'); return <tr key={`${day}-${date}`} className={`border-b border-[#102c24]/8 transition-colors last:border-0 hover:bg-[#f1f9e9] ${holiday ? 'bg-[#fffaf0]' : index % 2 ? 'bg-[#fbfdf9]' : 'bg-white'}`}><td className="px-5 py-4 align-top"><span className={`inline-flex min-w-9 justify-center rounded-full px-2.5 py-1 text-xs font-black ${holiday ? 'bg-[#ffe7b3] text-[#966315]' : 'bg-[#eaffd1] text-[#4d994b]'}`}>{day}</span></td><td className="whitespace-nowrap px-5 py-4 align-top text-sm font-bold text-[#315e3c]">{date}</td><td className="px-5 py-4 align-top text-sm font-semibold text-[#102c24]">{session}</td><td className="max-w-xs px-5 py-4 align-top text-sm leading-6 text-[#55716a]">{owner}</td></tr>})}</tbody></table></div><div className="flex items-center gap-2 border-t border-[#102c24]/8 bg-[#f7faf4] px-5 py-4 text-xs font-semibold text-[#6b8279]"><span className="h-2 w-2 rounded-full bg-[#e9b44c]" /> Holidays and open slots are highlighted so you can plan ahead.</div></div></div></section>

      <section id="journey" className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:py-28"><div className="overflow-hidden rounded-[2rem] bg-[#183b30] p-3 shadow-xl"><img src={images.stage} alt="New graduates gathered at the Esyasoft program stage" className="aspect-[.85] w-full rounded-[1.5rem] object-cover transition-transform duration-700 hover:scale-105 sm:aspect-[1.3] lg:aspect-[.85]" /></div><div><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">The bigger picture</p><h2 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">A journey, not a<br /><span className="text-[#59bd4e]">test.</span></h2><p className="mt-5 max-w-lg leading-7 text-[#55716a]">Over the next 30 days, you&apos;ll move from meeting the team to understanding the world we build for. Every day adds one small spark to your bigger picture.</p><div className="mt-8 space-y-3"><div className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaffd1] font-black text-[#4d994b]">01</span><div><p className="font-bold">Prosper</p><p className="text-sm text-[#71877f]">Build confidence and grow with purpose.</p></div></div><div className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8f7ef] font-black text-[#317f70]">02</span><div><p className="font-bold">Grow</p><p className="text-sm text-[#71877f]">Learn deeply and turn insight into action.</p></div></div><div className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#dbe8ff] font-black text-[#4f79b4]">03</span><div><p className="font-bold">Explore</p><p className="text-sm text-[#71877f]">Ask why and connect the dots.</p></div></div></div></div></section>

      <section id="community" className="relative z-10 bg-[#102c24] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-[#b8f73a]">You&apos;re not doing this alone</p><h2 className="max-w-xl text-4xl font-black tracking-[-.04em] sm:text-5xl">The best part of starting is finding your <span className="text-[#b8f73a]">people.</span></h2><p className="mt-5 max-w-lg leading-7 text-[#bad0c7]">Say hello in the room, join a coffee chat, or ask for a hand. Everyone here remembers their first day.</p><button className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#b8f73a] px-6 py-3.5 text-sm font-black text-[#102c24] transition hover:-translate-y-1 hover:bg-[#d3ff71]">Meet the community <ArrowRight size={17} /></button></div><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 p-3"><img src={images.community} alt="Esyasoft team and new graduates together" className="aspect-[1.25] w-full rounded-[1.5rem] object-cover" /><div className="absolute bottom-7 left-7 flex items-center gap-2 rounded-full bg-[#102c24]/85 px-3 py-2 text-xs font-bold backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#b8f73a]" /> Community is online</div></div></div></section>

      <section id="contact" className="relative z-10 bg-[#102c24] px-5 py-16 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#b8f73a]">Need a hand?</p><h2 className="mt-3 text-4xl font-black tracking-tight">Contact us.</h2><p className="mt-3 max-w-xl leading-7 text-white/70">Questions about your onboarding journey, sessions, or first-week setup? Reach out and we&apos;ll help you find the right person.</p></div><a href="mailto:prabhu.d@esyasoft.com" className="rounded-2xl bg-[#b8f73a] px-6 py-5 text-[#102c24] transition hover:-translate-y-1 hover:bg-white"><span className="block text-xs font-black uppercase tracking-[.15em]">Your onboarding contact</span><span className="mt-2 block text-xl font-black">Prabhu D</span><span className="mt-1 block text-sm font-semibold">prabhu.d@esyasoft.com</span></a></div></section>

      {aboutOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#071b15]/70 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="about-dialog-title"><div className="relative max-h-[90vh] w-full max-w-2xl overflow-auto rounded-[2rem] bg-[#f5f8f1] p-7 shadow-2xl sm:p-10"><button onClick={() => setAboutOpen(false)} className="absolute right-5 top-5 grid h-10 w-10 place-items-center rounded-full bg-white text-[#102c24] shadow-sm" aria-label="Close about Esyasoft"><X size={18} /></button><p className="text-xs font-black uppercase tracking-[.2em] text-[#62b95b]">About Esyasoft</p><h2 id="about-dialog-title" className="mt-3 max-w-lg text-4xl font-black tracking-[-.04em]">Building the future of <span className="text-[#59bd4e]">energy.</span></h2><p className="mt-5 leading-7 text-[#55716a]">Founded by Dr. Bipin Chandra, Esyasoft combines smart grids, IoT, AI, energy storage, and e-mobility to help utilities transition to a cleaner and more connected future.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><a href="#about" onClick={() => setAboutOpen(false)} className="rounded-2xl bg-[#102c24] p-4 font-bold text-white transition hover:-translate-y-1">Meet the company <ArrowRight className="ml-2 inline" size={16} /></a><a href="#policies" onClick={() => setAboutOpen(false)} className="rounded-2xl bg-white p-4 font-bold text-[#315e3c] transition hover:-translate-y-1">Read our policies <ArrowRight className="ml-2 inline" size={16} /></a></div></div></div>}

      <footer className="relative z-10 flex flex-col items-center justify-between gap-4 bg-[#102c24] px-5 pb-8 text-sm text-[#bad0c7] sm:flex-row sm:px-8"><span className="font-bold text-white">esya<span className="text-[#b8f73a]">soft</span> · Graduate Program 2026</span><span className="inline-flex items-center gap-2"><MessageCircle size={15} /> Questions are a superpower.</span></footer>
    </main>
  )
}

export { images }

// Short visual guide to supplied images: a green Graduate Program 2026 hero artwork with a friendly robot; a live event stage with a QR scavenger-hunt display; and two wide team/event photos showing the graduate cohort together.
